# Data Quality Principles

Companies House data quality principles align with the government data quality principles as defined in The Government Data Quality Framework, published 3 December 2020^[https://www.gov.uk/government/publications/the-government-data-quality-framework/the-government-data-quality-framework].

These principles are guidelines to aid the creation of a strong data quality culture in your team or organisation. They explain the best practice, procedures and attitudes that will be most helpful to ensuring your data is fit for purpose.

These principles should lie at the heart of your approach to data quality and be supported by the application of the products within the framework. Each principle is accompanied by a set of practices which support their adoption.

## Commit to data quality
Create a sense of accountability for data quality across your team or organisation, and make a commitment to the ongoing assessment, improvement and reporting of data quality.

### Embed effective data management and governance
Fit for purpose data depends on effective data management and governance practices.
Individuals and organisations should:

- adopt formal data governance practices to ensure that data is managed properly

- adhere to agreed data principles, such as those being developed as part of the National Data Strategy

- apply data standards to ensure that data is reusable and interoperable

- ensure that accountability for data quality is present at all levels:

    <!-- double indent is 4 spaces --> 
    - Data leaders should guide an organisation or team’s strategic direction by ensuring awareness and improvement of data quality

    - Data practitioners should ensure that measuring, communicating and improving data quality is at the forefront of activities relating to data

### Build data quality capability
Individuals and organisations should:

- dedicate time and resource to building capability in assessing, improving and communicating data quality through training and sharing best practice

- include best practice in data quality management (such as the data quality dimensions) as part of training materials

### Focus on continuous improvement
Continuous improvements can help to avoid data quality problems before they occur.
Individuals and organisations should:

- benchmark and regularly assess levels of data quality over time to track changes in quality

- prioritise and iterate effective improvements to achieve fit for purpose data

- use data quality action plans to identify and define where efforts should be prioritised

## Know your users and their needs
Understanding user needs is essential to ensuring that data is fit for purpose. Research and understand your users’ needs. Prioritise efforts on the data which is most critical.

### What is a user?
Users are the teams, businesses, services and people that will be making use of your data. For example, they may have business needs that rely on fit for purpose data from a trusted source, or they may be an enquiring member of the public looking to understand more about their local area.
You may have more than one type of user of your data. Different users’ needs may conflict, so it is important to balance these needs and prioritise having fit for purpose data. It is unlikely that data will be equally fit for all purposes.

More detailed information on users can be found in the GOV.UK Service Manual and, in the context of users of Official Statistics, in the forthcoming User Engagement Strategy for Statistics.

### Research your users and understand their quality needs
To achieve fit for purpose data, it is essential to understand your users’ quality needs.
Individuals and organisations should:

- proactively engage with users to understand their priorities

- carry out user research if faced with a large, complex or poorly understood group of users

- capture a range of user needs for data which has multiple uses

- balance the conflicting needs of users where possible and prioritise improvements which have the greatest impact

- regularly communicate with users to understand any changes in their requirements

## Assess quality throughout the data lifecycle
Data should be managed across its lifecycle, paying close attention to quality measures and assurance at each stage.

### What is a data lifecycle?
The data lifecycle is a way of describing the different stages the data will go through from design and collection to dissemination and archival/destruction. The flow of the data is not always sequential so you may need to return to previous stages to fix data quality issues.

The purpose of the data and its lifecycle should be well understood by anyone who handles the data, from its collection to the eventual output.
More detailed information is available in the data lifecycle section of the framework.

### Assess data quality at all stages of the lifecycle
Quality assurance should take place across the entire data lifecycle. Data quality issues can occur at any stage and can have knock-on effects for the rest of the lifecycle.
Individuals and organisations should:

- assess data quality at every stage and take proactive measures to improve quality when issues arise

- adopt appropriate assessment measures at each stage rather than applying a one-size-fits-all approach to quality assurance

- focus quality improvements as early in the lifecycle as possible to maximise their effectiveness

### Communicate with users and stakeholders across the lifecycle
Different stakeholders will often be involved across the data lifecycle.
Individuals and organisations should:

- develop effective communication channels with and between stakeholders to ensure a broad understanding of data quality

- communicate any changes in data quality to stakeholders at all stages of the lifecycle

- proactively engage with data providers to ensure a clear understanding of data quality requirements

## Communicate data quality clearly and effectively
Communicate quality to users regularly and clearly to ensure data is used appropriately.

### Communicate data quality to users

Individuals and organisations should:

- provide clear data quality information and describe its impact on use of the data

- communicate trade-offs in data quality clearly to aid understanding of the data’s strengths and weaknesses

- be transparent about the quality assurance approach taken and communicate data quality issues clearly to users

- build strong relationships with suppliers of external data to identify data quality problems at source

- inform users in advance about changes made to data processes which could impact on quality

- communicate clearly and in plain language, following relevant style guides for published materials

- provide clear definitions of terminology used and not presume a high level of user understanding of data quality

### Provide effective documentation and metadata
Individuals and organisation should:

- document and share metadata to minimise ambiguity and enhance opportunity for data access and reuse

- document and report data quality issues and be transparent about steps being taken to address them

## Anticipate changes affecting data quality
Not all future problems can be predicted. Where possible, anticipate and prevent future data quality issues through good communication, effective management of change and addressing quality issues at source.

### Plan for the future
Individuals and organisations should:

- use root cause analysis to solve data quality issues at source, rather than apply temporary fixes

- regularly communicate with users to keep up with changing data and quality requirements

- proactively consider the impact of changes in systems on data quality

- integrate quality processes into the design of new data systems

- ensure metadata and other supporting documentation is thorough and up to date
